/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Cpu.c
**     Project     : ProcessorExpert
**     Processor   : MKL26Z256VMC4
**     Component   : MKL26Z256MC4
**     Version     : Component 01.006, Driver 01.04, CPU db: 3.00.000
**     Datasheet   : KL26P121M48SF4RM, Rev.2, Dec 2012
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-03-01, 18:04, # CodeGen: 0
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#include "libbase/kl26/hardware.h"

#include <stdint.h>

#include "libbase/kl26/cmsis/system_MKL26Z4.h"
#include "libbase/kl26/mcg_c.h"
#include "libbase/kl26/vectors.h"

/* Flash configuration field */
__attribute__((__section__(".cfmconfig")))
const uint8_t _cfm[0x10] =
{
	/* NV_BACKKEY3: KEY=0xFF */
	0xFFU,
	/* NV_BACKKEY2: KEY=0xFF */
	0xFFU,
	/* NV_BACKKEY1: KEY=0xFF */
	0xFFU,
	/* NV_BACKKEY0: KEY=0xFF */
	0xFFU,
	/* NV_BACKKEY7: KEY=0xFF */
	0xFFU,
	/* NV_BACKKEY6: KEY=0xFF */
	0xFFU,
	/* NV_BACKKEY5: KEY=0xFF */
	0xFFU,
	/* NV_BACKKEY4: KEY=0xFF */
	0xFFU,
	/* NV_FPROT3: PROT=0xFF */
	0xFFU,
	/* NV_FPROT2: PROT=0xFF */
	0xFFU,
	/* NV_FPROT1: PROT=0xFF */
	0xFFU,
	/* NV_FPROT0: PROT=0xFF */
	0xFFU,
	/* NV_FSEC: KEYEN=1,MEEN=3,FSLACC=3,SEC=2 */
	0x7EU,
	/* NV_FOPT: ??=1,??=1,FAST_INIT=1,LPBOOT1=1,RESET_PIN_CFG=1,NMI_DIS=1,??=1,LPBOOT0=1 */
	0xFFU,
	0xFFU,
	0xFFU
};

void SystemInit(void)
{
	LibbaseKl26McgInit();

	InitVectorTable();
}
