/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Cpu.c
**     Project     : ProcessorExpert
**     Processor   : MK60DN512ZVLQ10
**     Component   : MK60N512LQ100
**     Version     : Component 01.000, Driver 01.04, CPU db: 3.00.001
**     Datasheet   : K60P144M100SF2RM, Rev. 5, 8 May 2011
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-01-15, 23:29, # CodeGen: 0
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#include "libbase/k60/hardware.h"

#include <stdint.h>

#include "libbase/k60/cmsis/system.h"
#include "libbase/k60/fpu_c.h"
#include "libbase/k60/mcg_c.h"
#include "libbase/k60/vectors.h"

/* Flash configuration field */
__attribute__((__section__(".cfmconfig")))
const uint8_t _cfm[0x10] =
{
	/* NV_BACKKEY3: KEY=0xFF */
	0xFFU,
	/* NV_BACKKEY2: KEY=0xFF */
	0xFFU,
	/* NV_BACKKEY1: KEY=0xFF */
	0xFFU,
	/* NV_BACKKEY0: KEY=0xFF */
	0xFFU,
	/* NV_BACKKEY7: KEY=0xFF */
	0xFFU,
	/* NV_BACKKEY6: KEY=0xFF */
	0xFFU,
	/* NV_BACKKEY5: KEY=0xFF */
	0xFFU,
	/* NV_BACKKEY4: KEY=0xFF */
	0xFFU,
	/* NV_FPROT3: PROT=0xFF */
	0xFFU,
	/* NV_FPROT2: PROT=0xFF */
	0xFFU,
	/* NV_FPROT1: PROT=0xFF */
	0xFFU,
	/* NV_FPROT0: PROT=0xFF */
	0xFFU,
	/* NV_FSEC: KEYEN=1,MEEN=3,FSLACC=3,SEC=2 */
	0x7EU,
	/* NV_FOPT: ??=1,??=1,??=1,??=1,??=1,??=1,EZPORT_DIS=1,LPBOOT=1 */
	0xFFU,
	/* NV_FEPROT: EPROT=0xFF */
	0xFFU,
	/* NV_FDPROT: DPROT=0xFF */
	0xFFU
};

void SystemInit(void)
{
	LibbaseK60McgInit();
#if __FPU_USED
	LibbaseK60FpuInit();
#endif

	InitVectorTable();
}
